### PR TITLE
Create User Password Fix

### PR DESCRIPTION
**Pull request by arghav**
Changed the password field in Form/UserForm to plainPassword.
Added getPlainPassword() to Model/User.php

### CODE REVIEW

**Comment by stof** [comment]
Why did you add a getPlainPassword method ? Imho It is useless as we don't want to get it. It is a bad practice to populate a password field and the only moment this attribute is not null is when we create a user (or change his password) as it is not persisted

**Comment by arghav** [comment]
@stof

Yes I agree, it was just a quick work around. So what do you suggest?

**Comment by stof** [comment]
Deleting this new method.
Or if it is needed by the form (I haven't really used Sf2 forms by now) returning an empty string.

**Comment by arghav** [comment]
Updated getPlainPassword() to return null.

Also changed the metadata for mongodb. **passwordHash** has to be **password**.

**Comment by ornicar** [comment]
Applied, thanks

**Pull request closed without merging**
